### PR TITLE
Moves `callback` invocation ahead of `throw` statement

### LINKED ISSUE #19: `CognitoExpress.init()` has an unreachable invocation of its `callback` parameter
The invocation of `callback` will never happen because a `throw` statement immediately precedes it.

https://github.com/ghdna/cognito-express/blob/86c738624b52a4de2e9e4df7bf10289564c3ae01/lib/strategy.js#L40-L45

### PR DESCRIPTION
**Pull request by robertbullen**
Fixes #19

Also converts the `catch()` handler from an anonymous function to an arrow function.

### CODE REVIEW

**Comment by robertbullen** [comment]
This fix should probably be considered a breaking change. This is because, as things work today, `callback` is invoked only when `init()` succeeds. If client code provides a `callback` that doesn't check the boolean argument and always assumes success, it could get into trouble.

Of course this decision should be made based on whether clients actually use `init()` or if it's considered more of an internal method. After all, `init()` is called by the constructor, subsequent invocations do nothing more than duplicate work, and `validate()` correctly picks up where `init()` left off. And all the examples in the readme leave out the call to `init()`.

**Comment by robertbullen** [comment]
And finally, the design of `init()` goes against convention. Typically, functions either invoke a callback when one is provided or return a promise, but not both. This is how `validate()` is written and `init()` should follow suit in future versions.

If this fix is considered a breaking change, then I suggest we scrap this PR and rewrite `init()` to follow the callback or promise convention.

**Comment by robertbullen** [comment]
Yet another reason to rewrite `init()`: Because the callback is executed from within `init()`'s promise body, the callback could affect the overall outcome of the returned promise. For example, if the callback throws, then the promise returned by `init()` will reject, even if `init()` completed its work successfully.

**Comment by deanshelton913** [comment]
This would help me out too

**Pull request merged**
