### PR TITLE
console error

### PR DESCRIPTION
**Pull request by jcardus**
I'm getting console errors from this project in my backend. The error is thrown so it will probably be logged twice.

### CODE REVIEW

**Comment by jcardus** [comment]
any news about this? also, token expired is not an error, it's perfectly normal to happen.

**Comment by avzabr** [comment]
@ghdna Would it be possible to review/release this fix? The `TokenExpiredError: jwt expired` spam is all the time in logs.

**Review by avzabr — APPROVED** [review]

**Comment by jcardus** [comment]
@avzabr I forked the project, it's on npm with the name fleetmap-cognito-express

**Comment by darrinholst** [comment]
Can we get this merged?

**Comment by Brendan-Stubbs** [comment]
Can this please be merged?

**Review by ghdna — APPROVED** [review]

**Comment by Brendan-Stubbs** [comment]
Thank you 👍

**Comment by ghdna** [comment]
Thanks for reminding me

**Pull request merged**
