### PR TITLE
Migrated the project to TypeScript and removed deprecated libraries

### PR DESCRIPTION
**Pull request by naishe**
This issue was opened by me https://github.com/ghdna/cognito-express/issues/9 to add typing to this project. This PR is for that. The PR also upgrades the library dependencies and gets rid of deprecated library that's still being used. Here is the summary

1. Updated the project to Typescript
2. Adds appropriate types and gets rid of inconsistencies like throwing `Error` vs throwing a string.
3. Libraries like `request`, `request-promise`, and `istanbul` are deprecated, replaced them with `fetch` and `nyc`
4. Expanded test coverage

I haven't tested this version extensively, but I am using a version of congnito-express with very similar changes for a almost two years without hiccup.

I am open to suggestions.

### CODE REVIEW

**Comment by naishe** [comment]
Some testing is required.

**Comment by ghdna** [comment]
is this good to be tested?

**Comment by naishe** [comment]
@ghdna -- there are some tests remaining. I will update in the coming week.

**Comment by frnlucas** [comment]
Why this PR was not merged? Is this change working? It would be nice to use the lib with TypeScript.

**Comment by robertwilkinson-dev** [comment]
for people like me that just wanted a quick way to validate a user is authenticated; just use `aws-jwt-verify` as there seems to be resistance to making this library type safe for some reason

**Comment by Antonio-Riccelli** [comment]
Will this ever be merged?

**Pull request closed without merging**
